;;; crdt-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from crdt.el

(autoload 'crdt-list-sessions "crdt" "\
Display a list of active CRDT sessions.
If DISPLAY-BUFFER is provided, display the output there.

(fn &optional DISPLAY-BUFFER)" t)
(autoload 'crdt-list-buffers "crdt" "\
Display a list of buffers shared in SESSION.

(fn &optional SESSION)" t)
(autoload 'crdt-list-users "crdt" "\
Display a list of active users working on a SESSION.

(fn &optional SESSION)" t)
(autoload 'crdt-share-buffer "crdt" "\
Share the current buffer in the CRDT session with name SESSION-NAME.
Create a new one if such a CRDT session doesn't exist.

(fn SESSION-NAME)" t)
(autoload 'crdt-connect "crdt" "\
Connect to a CRDT server running at URL.
Open a new buffer to display the shared content.
Join with DISPLAY-NAME.

(fn URL DISPLAY-NAME)" t)
(register-definition-prefixes "crdt" '("add" "challenge" "contact" "crdt-" "cursor" "delete" "error" "fcap" "funcall" "get" "insert" "leave" "login" "overlay-" "process" "ready" "remove" "return" "sync" "var"))

;;; End of scraped data

(provide 'crdt-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; crdt-autoloads.el ends here
